## Science High School Passers 2026 - 2027

Source: https://drive.google.com/file/d/1Lv1amfrQnutRdglRGUOA5-fRqNLdV0LN/view

### Imports

#### Libraries/Packages

In [2]:
import pdfplumber
import pandas as pd

#### Data

In [3]:
FILE_PATH = r"./RM No. 277 s. 2026 - Released of the List of Qualifiers Eligible for Enrollment to NCR Science High Schools, SY 2026 - 2027.pdf"

In [4]:
# Open PDF and iterate through all pages to extract tables
with pdfplumber.open(FILE_PATH) as pdf:
    data = [page.extract_table() for page in pdf.pages if page.extract_table()]

In [21]:
DFS = [pd.DataFrame(table) for table in data]

In [22]:
DF_COMBINED = pd.concat(DFS, ignore_index=True)

In [26]:
DF_COMBINED = DF_COMBINED.drop_duplicates(keep="first")

In [31]:
DF_COMBINED[~DF_COMBINED[3].isnull()]

,0,1,2,3
2828,,Absorptive Capacity: 315,Waitlisted: 63,
2829,,,,
2832,,FULLNAME,ELEMENTARY SCHOOL,CHOICE NO
2833,1,"Rosario, Nadine Elizabeth M.",Saint Theresa's College of Quezon City,1st
2834,2,"Santiago, Francis Paolo V.",Fairview Baptist Academy,1st
...,...,...,...,...
3233,374,"Domantay, Nash Apollo J.",Discovery House of Montessori of Quezon City,2nd
3234,375,"Evangelista, Christian Liam L.","Martires Intergated Academy, Inc.",2nd
3235,376,"De Guzman, Ysabella Claire D.",Holy Child Academy,1st
3236,377,"Galaura, John Rafael A.",San Miguel Elementary School,2nd
3237,378,"Mazo, Hance Dave E.",Andres Bonifacio Elementary School,2nd

In [10]:
pd.DataFrame(data[1])

,0,1,2
0,,Caloocan City Science High School,None
1,27,"Hamot, Dayne Nathaniel E.",Malinta Elementary School
2,28,"Estrada, Mark Jared A.",Marulas Central School
3,29,"Villedo, Czarina Yuri",Placido Del Mundo Elementary School
4,30,"Saravillo, Kent Andrei M.",Claret School of Quezon City
5,31,"Banzon, Zaenhard Zilljan C.",Placido Del Mundo Elementary School
6,32,"Marinas, Savanna Rianne S.",Montessori Academy of Valenzuela
7,33,"Jorge, Aamir Daniken C.",Malinta Elementary School
8,34,"Acebu, John Chaleb C.",Center of Excellence Manila
9,35,"Taculog, Khierstynne Aerith B.",Mind At Work Progressive School Inc.
10,36,"Alpon, Izabelle M.",Santiago A. De Guzman Elementary School
11,37,"Jamolangue, Chanaya R.",Rosa L. Susano Novaliches Elementary School
12,38,"Franco, Ma. Marxine Elisse L.",Fransisco Benitez Elementary School
13,39,"Japlit, Gavin Santiago S.",The Seed Montessori School of Quezon City
14,40,"Totanes, Vinz Joaquin",La Naval Academy
15,41,"Llana, One Samuel A.",Capstone Highest Achiever Learning School
16,42,"Catayoc, Sophia May R.",St. Joseph College of Novaliches Inc.
17,43,"Agasen, Prince Lance A.",Libis Talisay Elementary School
18,44,"Agana, Abraham P.",Notre Dame of Greater Manila
19,45,"Bautista, Erich Nathalie H.",Perpetual Help Learning Academy
20,46,"Cristobal, Fermin Iii S.",Diliman Preparatory School
21,47,"Perez, Liam Gavin L.",Felipe G. Calderon Elementary Integrated School
22,48,"Celis, Savannah Venieze",Pasig Elementary School
23,49,"Dizon, Zaria Ysabelle C.",Learning Journey Child Growth Center
24,50,"Tingin, Reighl M.","Escuela De Sophia of Caloocan, Inc."
25,51,"Ningas, Rye Maru J.",Roberta De Jesus Elementary School
26,52,"Galit, Charlotte Rose C.",Caloocan Bethel Christian School
27,53,"Marquez, Leighla Patricia Candice M.",Good Shepherd Cathedral School
28,54,"Sampang, Jedi P.",Sto. Nino Elementary School
29,55,"Laguting, Zara Sofia F.",Project 6 Special Science Elementary School
30,56,"Albay, Jian Rafael D.",Notre Dame of Greater Manila
31,57,"De Vera, Maxene Sofia R.",Master Hand School